### ISSUE TITLE
[ONBOARDING] Jest

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/project-status#67]
## Project Onboarding Checklist - Jest

**Stage: At Large (post incubation)**

- [x] Adopt the [OpenJS Foundation Code of Conduct](https://code-of-conduct.openjsf.org/) https://github.com/jestjs/jest/issues/14899
- [x] Update project CoC reporting methods to include OpenJS Foundation escalation path https://github.com/jestjs/jest/issues/14899
- [x] List official domains that the project commits to transfer to the OpenJS Foundation following graduation
- [x] Identify and document other core project infrastructure https://github.com/jestjs/jest/issues/14921
- [x] Adopt either the [Contributor License Agreement (CLA) or the Developer Certificate of Origin (DCO)](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/governance/IP_POLICY_GUIDANCE.md#4-adopting-the-dco-or-a-cla)
- [x] ~~Add or Update Governance.md document (required for Impact stage)~~
- [x] Confirm required files in place (CODE_OF_CONDUCT.md, LICENSE.md)
- [x] Publish Project Charter on website or GitHub (see [charter template](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/PROJECT_CHARTER_TEMPLATE.md)) https://github.com/jestjs/jest/issues/14927
- [x] Update [legal copyright notice](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/governance/IP_POLICY_GUIDANCE.md#2-copyright-notices) on GitHub https://github.com/jestjs/jest/pull/14922
- [x] Add [copyright notices for project website footers](https://github.com/openjs-foundation/artwork#copyright-notices-for-project-website-footers) to project website https://github.com/jestjs/jest/issues/14903
- [x] Add [OpenJS Foundation logo](https://github.com/openjs-foundation/artwork#openjs-foundation-logos) to project website https://github.com/jestjs/jest/issues/14903
- [x] [Add Project logo](https://github.com/openjs-foundation/artwork#preparing-artwork-for-contribution) to OpenJS Foundation website
- [x] Add Project to the [CPC repo's README.md](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/README.md#incubating-projects) as an Incubating project
- [x] List trademarks the project commits to transfer to the OpenJS Foundation following graduation
- [x] ~~If project is using crowdfunding platforms, add disclaimer from the OpenJS Foundation [Trademark Policy](https://trademark-policy.openjsf.org/) to platforms~~
- [x] Identify individuals from the project to join the CPC [by opening an issue in the CPC repository](https://github.com/openjs-foundation/cross-project-council/issues/new)
- [x] Document project and foundation contacts for:
  - [x] marketing & social media
  - [x] infrastructure
  - [x] legal/governance help
- [x] Publish security policy (see [PROJECT_SECURITY_REPORTING](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/PROJECT_SECURITY_REPORTING.md)) https://github.com/jestjs/jest/issues/14926

**Comment by bensternthal** [comment]
@tobie & @joesepi I'd like to file a PR against the jest repo with an OpenJS compatible COC policy. I did not find a template for this. Would it be acceptable to use [Fastify's](https://github.com/fastify/.github/blob/main/CODE_OF_CONDUCT.md) as an example and just customize the top section on reporting?

**Comment by tobie** [comment]
Is Jest planning to opt-in to manage CoC violation reports directly or will this fall to the CoC Team?

We should definitely have better material and clearer instructions for how to adopt the foundation's CoC.

**Comment by bensternthal** [comment]
Unknown, I asked in the [issue](https://github.com/jestjs/jest/issues/14899). Depending on their answer I can draft a policy based on an existing version. I can use Fastify, or if you have another one you would prefer, let me know.

**Comment by bensternthal** [comment]
@tobie they will want the COC team to handle these reports.

**Comment by tobie** [comment]
I like @ljharb's answer in https://github.com/openjs-foundation/cross-project-council/issues/1251#issuecomment-1947905224: reference the foundation's CoC (https://code-of-conduct.openjsf.org/) from your CoC file.

**Comment by Pissedmommy** [comment]
I really appreciate u smart o watch my mouth.  I have a thing coming up and I'm lost. Noone will help , me. I may not deserve it.  But one day I won't be here. The idea of being part of something for the good has really inspired me. I need a tutor or someone willing to get deep in some interesting stuff.  Anyone willing will be at a job making a decent living and lives better. ,,,,also ivappologize i feel an urgency to figure this out. And move foward either way. Itam goong to take a long time to catch on to the first sentemce  and i intend to thank and support u gits either way. Feel gurèe to email or which ever isvappropriate as to not over step..

**Comment by bensternthal** [comment]
All items are complete. Closing!
